# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ... } : {
  imports = [
    ../../home
  ];

  home.packages = with pkgs; [
    brightnessctl
  ];

  wayland.windowManager.hyprland.settings = {
    bind = [
      ", XF86MonBrightnessUp, exec, brightnessctl set 5%+"
      ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
      ", XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ", XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    ];

    bindl = [
      '', switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"''
      '', switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, 2560x0, 2"''
    ];

    monitor = [
      "desc:AOC Q3279WG5B 0x00000161, preferred, 0x0, 1, vrr, 2"      # main monitor
      "eDP-1, preferred, 2560x0, 2"  # laptop monitor
    ];

    workspace = [
      "1,monitor:desc:AOC Q3279WG5B 0x00000161, default:true"
      "2,monitor:desc:AOC Q3279WG5B 0x00000161, default:true"
      "5,monitor:eDP-1, default:true"
    ];

    windowrule = [
      "workspace:1, class:firefox"
      "workspace:2, class:emacs"
      "workspace:5, class:Slack"
    ];

    exec-once = [
      "[workspace 1 silent] firefox"
      "[workspace 2 silent] emacs"
      "[workspace 5 silent] slack"
    ];
  };
}
