# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  system = "x86_64-linux";
  username = "nambiar";
  stateVersion = "25.05";
  locale = "sv_SE.UTF-8";
}
