# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  hostname,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../hardware/hardware.nix
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/911d76da-1990-4e83-aefb-fa116e9cd0ee";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BAD3-5A84";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/18818348-1ee4-4fa5-9984-e4e01b9fa304";
    fsType = "ext4";
  };

  swapDevices = [ ];

  hardware.sane.enable = true;
  hardware.sane.extraBackends = [
    pkgs.sane-airscan
    pkgs.utsushi
  ];
  services.udev.packages = [ pkgs.utsushi ]; # scanner backend for epson

  networking.hostName = hostname; # this machine is available as "bigbox" on the network
}
