# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  imports = [
    ../../home
  ];

  wayland.windowManager.hyprland.settings = {
    monitor = [
      "HDMI-A-1, 2560x1440@60, 0x0, 1, vrr, 2"      # main monitor
      "DP-2, 3840x2160, 2560x0, 1.5, transform, 1"  # side monitor on the right, vertical
    ];

    workspace = [
      "1,monitor:HDMI-A-1"
      "2,monitor:HDMI-A-1"
      "5,monitor:DP-2"
    ];

    exec-once = [
      "[workspace 1 silent] firefox"
      "[workspace 2 silent] emacs"
      "[workspace 5 silent] slack"
    ];
  };
}
