# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, user, ... } :
{
  imports = [
    ./waybar.nix
    ./wallpaper.nix
    ./lock.nix
    ./unity.nix
    ./hyprland.nix
    ./walker.nix
    ./theme.nix
    ./terminal.nix
    ./dev.nix
    ./emacs
  ];

  home.username = "${user.username}";
  home.homeDirectory = pkgs.lib.mkDefault "/home/${user.username}";
  home.stateVersion = user.stateVersion;

  home.packages = with pkgs; [
    audacity                 # audio recording
    zoom-us                  # meetings
    handbrake                # video transcoding
    xdg-utils                # utils, for screensharing
    vlc                      # media player
    discord                  # other chat
    slack                    # work chat
    pavucontrol              # audio control
    everdo                   # gtd tool
    spotify                  # music player
    simple-scan              # scanner software
    pinta                    # image editor
    mpv                      # media player
  ];

  services.dunst.enable = true;      # notifications daemon

  programs.obs-studio.enable = true; # screen recording tool

  programs.home-manager.enable =  true;
}
