# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  # required for the default Hyprland config
  programs.kitty.enable = true;

  services.hyprpolkitagent.enable = true;

  # enable Hyprland
  wayland.windowManager.hyprland.enable = true;

  # we start hyprland using uwsm
  wayland.windowManager.hyprland.systemd.enable = false;

  # hyprland.conf
  wayland.windowManager.hyprland.settings = {
    exec-once = [
      # read in env vars
      "dbus-update-activation-environment --systemd --all"
      # start waybar
      "uwsm app -- waybar"
      # start the policykit agent
      "uwsm app -- lxqt-policykit-agent"
    ];

    input = {
      follow_mouse = "1";

      touchpad = {
        natural_scroll = "no";
        scroll_factor = 0.5;
      };

      accel_profile =  "adaptive";
      sensitivity = -0.5; # -1.0 - 1.0, 0 means no modification.

      kb_layout = "us";

      # very emacs specific, i use caps as an extra ctrl key
      kb_options = "ctrl:nocaps";
    };

    cursor = {
      no_hardware_cursors = "true";
    };

    general = {
      gaps_in = 2;
      gaps_out = 4;
      border_size = 2;
      "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
      "col.inactive_border" = "rgba(595959aa)";

      layout = "dwindle";
    };

    decoration = {
      rounding = 5;
    };

    animations = {
      enabled = "yes";
      bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";

      animation =  [
        "windows, 1, 7, myBezier"
        "windowsOut, 1, 7, default, popin 80%"
        "border, 1, 10, default"
        "borderangle, 1, 8, default"
        "fade, 1, 7, default"
        "workspaces, 1, 6, default"
      ];
    };

    dwindle = {
      pseudotile = "yes";
      preserve_split = "yes";
    };

    gestures = {
      workspace_swipe = "off";
    };

    misc = {
      disable_hyprland_logo = true;
      focus_on_activate = true;
    };

    "$mainMod" = "SUPER";

    bind = [
      "$mainMod, Return, exec, uwsm app -- alacritty"
      "$mainMod_SHIFT, Q, killactive"
      "$mainMod_SHIFT, M, exit"
      "$mainMod, F, exec, thunar"
      "$mainMod_SHIFT, Space, togglefloating"

      # use tofi to show exec menu
      "$mainMod, Space, exec, uwsm app -- tofi-run | xargs hyprctl dispatch -- exec"
      "$mainMod, P, pseudo"
      "$mainMod, J, togglesplit"

      "$mainMod_SHIFT, left, movewindow, l"
      "$mainMod_SHIFT, right, movewindow, r"
      "$mainMod_SHIFT, up, movewindow, u"
      "$mainMod_SHIFT, down, movewindow, d"

      "$mainMod, left, movefocus, l"
      "$mainMod, right, movefocus, r"
      "$mainMod, up, movefocus, u"
      "$mainMod, down, movefocus, d"

      "$mainMod, mouse_down, workspace, e+1"
      "$mainMod, mouse_up, workspace, e-1"

      "$mainMod_SHIFT, S, exec, wlogout"
    ] ++ (
      # workspaces
      # binds $mod + [shift +] {1..9} to [move to] workspace {1..9}
      builtins.concatLists (builtins.genList (i:
        let ws = i + 1;
        in [
          "$mainMod, ${toString ws}, workspace, ${toString ws}"
          "$mainMod SHIFT, ${toString ws}, movetoworkspace, ${toString ws}"
        ]
      )
        9)
    );

    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
  };

  programs.hyprlock = {
    enable = true;

    # hyprlock.conf
    settings = {
      background = {
        monitor = "";
        path = "~/.background-image.png";
        blur_passes = 2;
        contrast = 1;
        brightness = 0.5;
        vibrancy = 0.2;
        vibrancy_darkness = 0.2;
      };

      auth = {
        fingerprint = {
          enabled = true;
        };
      };

      # GENERAL
      general = {
        hide_cursor = false;
        grace = 0;
      };

      # INPUT FIELD
      input-field = [
        {
          size = "250, 60";
          outline_thickness = 2;
          dots_size = 0.2;
          dots_spacing = 0.35;
          dots_center = true;
          outer_color = "rgba(216,222,233,0.2)";
          inner_color = "rgba(216,222,233,1)";
          font_color = "rgba(41,46,57,1)";
          fade_on_empty = false;
          rounding = -1;
          check_color = "rgb(163,190,140)";
          placeholder_text = ''<i><span>Password</span></i>'';
          hide_input = false;
          position = "0, -400";
          halign = "center";
          valign = "center";
        }
      ];

      # DATE
      label = [
        {
          monitor = "";
          text = ''cmd[update:1000] echo "$(date +"%A, %B %d")"'';
          color = "rgba(242, 243, 244, 0.75)";
          font_size = 22;
          font_family = "Iosevka";
          position = "0, 300";
          halign = "center";
          valign = "center";
        }
        # TIME
        {
          monitor = "";
          text = ''cmd[update:1000] echo "$(date +"%-I:%M")"'';
          color = "rgba(242, 243, 244, 0.75)";
          font_size = 95;
          font_family = "Iosevka";
          position = "0, 200";
          halign = "center";
          valign = "center";
        }
        # USER
        {
          monitor = "";
          text = ''cmd[update:1000] echo $USER'';
          color = "rgba(242, 243, 244, 0.75)";
          font_size = 30;
          font_family = "Iosevka";
          position = "0, -250";
          halign = "center";
          valign = "center";
        }

        # battery
        {
          monitor = "";
          text = ''cmd[update:1000] echo "$(cat /sys/class/power_supply/BAT0/capacity) 󰁹"'';
          color = "rgba(242, 243, 244, 0.75)";
          font_size = 20;
          font_family = "Iosevka";
          position = "-20, -20";
          halign = "right";
          valign = "top";
        }
      ];

      # Profile Picture
      image = [
        {
          monitor = "";
          path = "~/.me.jpg";
          size = 200;
          border_size = 2;
          position = "0, -100";
          halign = "center";
          valign = "center";
        }
      ];
    };
  };
}
