# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ... } :
{
  home.packages = with pkgs; [
    swaylock
    swayidle
    wlogout
  ];

  programs.swaylock.enable = true;

  home.file = {
    lock = {
      source = ../assets/lock.png;
      target = ".lock.png";
    };
  };

  programs.swaylock.settings = {
    image = "~/.lock.png";
    ignore-empty-password = true;
    show-failed-attempts = true;
    font = "Iosevka";
  };

  services = {
    # swayidle to lock using swaylock after 180 seconds
    # suspend after 10 minutes
    # lock before suspend
    swayidle = {
      enable = true;
      timeouts = [
        {
          timeout = 185;
          command = "swaylock";
        }
        {
          timeout = 600;
          command = "systemctl suspend";
        }
      ];
      events = [
        {
          event = "before-sleep";
          command = "swaylock";
        }
      ];
    };
  };

  programs.wlogout = {
    enable = true;
    layout = [
      {
        "label"  = "lock";
        "action" = "swaylock";
        "text" = "Lock";
        "keybind" = "l";
      }
      {
        "label" = "shutdown";
        "action" = "systemctl poweroff";
        "text" = "Shutdown";
        "keybind" = "s";
      }
      {
        "label" = "suspend";
        "action" = "swaylock & sleep 1 ; systemctl suspend";
        "text" = "Suspend";
        "keybind" = "u";
      }
      {
        "label" = "reboot";
        "action" = "systemctl reboot";
        "text" = "Reboot";
        "keybind" = "r";
      }
      {
        "label" = "hibernate";
        "action" = "systemctl hibernate";
        "text" = "Hibernate";
        "keybind" = "h";
      }
      {
        "label" = "reboot";
        "action" = "systemctl reboot";
        "text" = "Reboot";
        "keybind" = "r";
      }
    ];
  };
}
