# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  programs = {
    alacritty = {
      enable = true;
      settings = {
        font.normal.family = "Aporetic Sans Mono";
        font.size = 12;
        terminal.shell.program = "zsh";

        window = {
          padding.x = 4;
          padding.y = 4;
        };
      };
    };
  };

  catppuccin.alacritty.enable = true;
  catppuccin.alacritty.flavor = "mocha";
}
