# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ...}:
{
  gtk = {
    enable = true;
    colorScheme = "dark";
    theme = {
      name = "Catppuccin-GTK-Grey-Dark-Compact";
      package = (pkgs.magnetic-catppuccin-gtk.override {
        accent = [ "grey" ];
        shade = "dark";
        tweaks = [ "black" ];
        size = "compact";
      });
    };

    iconTheme.name = "Papirus-Dark";
  };

  catppuccin.enable = true;
  catppuccin.flavor = "mocha";
  catppuccin.accent = "blue";
  catppuccin.gtk.icon.enable = true;
  catppuccin.cursors.enable = true;
}
