# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ...}:
{
  home.packages = with pkgs; [
    nordzy-cursor-theme
    nordic
  ];

  gtk = {
    enable = true;
    iconTheme = {
      name = "Nordic-bluish";
      package = pkgs.nordic;
    };
    theme = {
      name = "Nordic";
      package = pkgs.nordic;
    };
    cursorTheme = {
      name = "Nordzy-cursors";
      package = pkgs.nordzy-cursor-theme;
    };
  };
}
