# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  programs.tofi.enable = true;
  programs.tofi.settings = {
    font = "Iosevka";
    font-size = 16;
    selection-color = "#a3be8c";
    prompt-text = ":";
    width = 600;
    height = 480;
    background-color = "#2e3440";
    outline-width = 0;
    outline-color = "#080800";
    border-width = 1;
    border-color = "#8fbcbb";
    corner-radius = 10;
    padding-top = 4;
    padding-bottom = 4;
    padding-left = 4;
    padding-right = 4;
    matching-algorithm = "fuzzy";
  };
}
