# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ... }:
{
  home.packages = with pkgs; [
    (pkgs.unityhub.override {
      extraPkgs = pkgs: with pkgs; [
        dotnet-sdk
      ];
    })
  ];
}
