# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  services.walker.enable = true;
  services.walker.settings = {
    close = "ctrl g";
    next = "ctrl n";
    previous = "ctrl p";
    quick_activate = ["1" "2" "3" "4"];
  };
}
