# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ config, pkgs, ... }:
{
  boot.kernelParams = [
    "nvidia-drm.modeset=1" # nvidia needs "Direct Rendering Manager" kernel mode to work with wayland.
    "nvidia-drm.fbdev=1" # it also needs kernel frame buffer as well. Dont ask why.
  ];

  hardware.graphics.extraPackages = with pkgs; [
    vaapiVdpau # video acceleration on nvidia graphics
    libvdpau-va-gl # vdpau driver with opengl backend
  ];

  hardware.nvidia = {
    modesetting.enable = true; # lets the driver set kernel mod settings autoamagically
    powerManagement.enable = true; # allows the gpu to be switched of when not needed.
    powerManagement.finegrained = false; # even finegrained, per app

    open = false; # use proprietary drivers
    nvidiaSettings = true; # install the nvidia-settings app

    # latest greatest driver always
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };

  # add vulkan headers and tools to the system
  environment.systemPackages = with pkgs; [
    vulkan-headers
    vulkan-loader
    vulkan-tools
  ];

  # this enables the nvidia gpu. even for wayland.
  services.xserver.videoDrivers = [ "nvidia" ];
}
