# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, user, ... } :
{
  imports = [
    ./boot.nix
    ./login.nix
    ./cli.nix
    ./files.nix
    ./locale.nix
    ./nix-settings.nix
    ./networking.nix
    ./hyprland.nix
    ./services.nix
    ./audio.nix
    ./steam.nix
    ./sops.nix
  ];

  environment.systemPackages = with pkgs; [
    wget       # fetch utility
    curl       # more fetch utility
    binutils   # executable utilities, like ld
    dmidecode  # tool for dumping system info
    libnotify  # notification daemon
    python3    # nice to have this ready for quick things
    cacert     # certificate authority
    remmina    # remote desktop app
  ];
  
  # to enable icons with wlogout
  # https://github.com/catppuccin/nix/issues/584
  programs.gdk-pixbuf.modulePackages = [ pkgs.librsvg ];

  users.users.${user.username} = {
    isNormalUser = true;
    description = "Sandeep Nambiar";
    extraGroups = [
      "networkmanager" # allow editing network connections
      "wheel"          # can do sudo
      "scanner"        # access to the network scanner
      "lp"             # access to the printer
    ];
  };

  programs = {
    nix-ld.enable = true;   # helps with linking troubles with dynamic libraries
    appimage.enable = true; # allow appimage installations
    dconf.enable = true;    # to save user settings
    gnupg.agent = {
      # pgp client
      enable = true;
      enableSSHSupport = true;
    };
    firefox.enable = true;   # browser
    wireshark.enable = true; # vpn
  };

  fonts.packages = with pkgs; [
    aporetic
    nerd-fonts.iosevka
  ];

  # enable the catppuccin theme for everything with mocha + blue accents
  catppuccin.enable = true;
  catppuccin.flavor = "mocha";
  catppuccin.accent = "blue";

  system.stateVersion = user.stateVersion;
}
