# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ pkgs, ... } : {
  networking = {
    # allow automatic ip assignment when connecting to a network
    useDHCP = pkgs.lib.mkDefault true;
    networkmanager.enable = true;
    firewall.enable = true;

    # let wifi info be NOT declarative, allowing user to configure wifi.
    wireless.userControlled.enable = true;
    wireless.iwd.enable = true;
    networkmanager.wifi.backend = "iwd";
  };

  # tui to manage wifi networks
  environment.systemPackages = with pkgs; [ impala ];
}
