# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  networking = {
    networkmanager.enable = true;
    firewall.enable = true;
  };
}
