# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ user, ...} :
{
  services = {
    blueman.enable = true;                # bluetooth manager
    fwupd.enable = true;                  # firmware updating service
    fstrim.enable = true;                 # ssd maintenance service
    thermald.enable = true;               # thermal regulation service
    printing.enable = true;               # printing services, cups
    gnome.gnome-keyring.enable = true;    # keyring
    flatpak.enable = true;                # allow installing things from flatpaks

    # printer discovery
    avahi = {
      enable = true;
      nssmdns4 = true;
      openFirewall = true;
    };

    # syncthing
    syncthing = {
      enable = true;
      openDefaultPorts = true;
      user = "${user.username}";
      configDir = "/home/${user.username}/.conifg/syncthing";
      settings = {
        devices = {
          "phone" = { id = "AC6CP4C-TBXMOU5-DSLTDSJ-B2ZJ65D-EXILKVV-U4QEDVA-AIAJZNJ-MX2RHQP"; };
        };

        folders = {
          "OrgSync" = {
            path = "/home/${user.username}/org";
            devices = [ "phone" ];
            ignorePerms = true;
          };
        };
      };
    };
  };

  systemd.services.syncthing.environment.STNODEFAULTFOLDER = "true"; # Don't create default ~/Sync folder

  virtualisation.docker.enable = true;    # enable docker
  users.users.${user.username}.extraGroups = [ "docker" ];
}
