# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{ user, ...} :
{
  sops.secrets.wireguard_coherence = {
    owner = "${user.username}";
  };
  networking.wg-quick.interfaces.wg0.configFile = "/run/secrets/wireguard_coherence";
}
