# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  imports = [
    ../../home
  ];

  wayland.windowManager.hyprland.settings = {
    monitor = [
      ",highres,auto,2,bitdepth,10"
    ];

    xwayland = {
      force_zero_scaling = true;
    };

    exec-once = [
      "[workspace 1 silent] firefox"
      "[workspace 2 silent] emacs"
      "[workspace 5 silent] slack"
    ];
  };
}
